-- Tabela de Voluntários
CREATE TABLE VOLUNTARIOS (
    ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(100),
    PRIMARY KEY (ID)
);

-- Tabela de Gerentes
CREATE TABLE GERENTES (
    ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(100),
    PRIMARY KEY (ID)
);